@url = https://stuagwhol0.execute-api.us-east-1.amazonaws.com/prod

GET {{url}}/spaces
###

POST {{url}}/spaces
Content-Type: application/json

{
    "location": "DunDalk",
    "name": "County"
}
###

GET {{url}}/spaces?id=a48d717d-3193-49d9-a261-5cba09265012
###

PUT {{url}}/spaces?id=a48d717d-3193-49d9-a261-5cba09265012

{
    "location": "Killarney Kerry"
}
###

DELETE {{url}}/spaces?id=4424659b-96a5-48b7-ba15-f92f70394251
###